#!/bin/bash
# build-deb.sh — build Debian packages for tt-toplike-rs
#
# This script handles the full packaging flow:
#   1. Vendors all crate dependencies into vendor/ (required for offline builds)
#   2. Writes .cargo/config.toml to redirect cargo to the vendor directory
#   3. Runs dpkg-buildpackage to produce signed-off .deb files
#
# Usage:
#   ./build-deb.sh           # build tt-toplike and tt-toplike-app
#   ./build-deb.sh --quick   # skip re-vendoring (vendor/ already present)
#
# Output: ../tt-toplike_*.deb and ../tt-toplike-egui_*.deb
#
# Prerequisites:
#   sudo apt install devscripts debhelper rustc cargo
#
# To also use cargo-deb for quick single-package iteration:
#   cargo install cargo-deb
#   cargo deb                     # builds tt-toplike TUI package
#   cargo deb --bin tt-toplike-egui --features egui

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ── Parse arguments ───────────────────────────────────────────────────────────
SKIP_VENDOR=false
for arg in "$@"; do
    case "$arg" in
        --quick) SKIP_VENDOR=true ;;
        --help|-h)
            sed -n '2,20p' "$0" | sed 's/^# //'
            exit 0
            ;;
    esac
done

# ── Check prerequisites ───────────────────────────────────────────────────────
for cmd in cargo dpkg-buildpackage dh; do
    if ! command -v "$cmd" &>/dev/null; then
        echo "ERROR: '$cmd' not found. Install with:"
        echo "  sudo apt install devscripts debhelper rustc cargo"
        exit 1
    fi
done

echo "╔══════════════════════════════════════════╗"
echo "║  tt-toplike-rs Debian package builder    ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── Step 1: Vendor crate dependencies ─────────────────────────────────────────
# All crates must be vendored so that dpkg-buildpackage can build without
# network access. This mirrors how the Debian build daemons work.
if [ "$SKIP_VENDOR" = true ] && [ -d vendor ]; then
    echo "⏭  Skipping vendor (--quick, vendor/ already exists)"
else
    echo "📦 Vendoring crate dependencies (this may take a minute)..."

    # Remove stale vendor dir if present
    rm -rf vendor

    # IMPORTANT: also remove .cargo/config.toml before vendoring.
    # If it exists and points at vendor/, cargo vendor treats it as an
    # incremental update of the existing source and skips writing
    # Cargo.toml.orig files — which the checksum verifier requires.
    # We rewrite it in Step 2 after vendor/ is fully populated.
    rm -f .cargo/config.toml

    # cargo vendor populates vendor/ and prints the config snippet to stdout
    cargo vendor vendor/ 2>&1 | grep -v "^$" || true

    echo "   Vendored $(find vendor -name '*.toml' -maxdepth 2 | wc -l) crates"
    echo "   .orig files: $(find vendor -name '*.orig' | wc -l)"
fi

# ── Step 2: Write .cargo/config.toml ─────────────────────────────────────────
# This redirects cargo source lookups to vendor/ instead of crates.io.
# The file is NOT committed to git (see .gitignore) — it's generated here
# because its path depends on the vendor location.
mkdir -p .cargo
cat > .cargo/config.toml <<'EOF'
# Generated by build-deb.sh — do not edit manually.
# Redirects all crate lookups to the local vendor/ directory for
# reproducible, network-free builds (required for dpkg-buildpackage).
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF

echo "✍  Wrote .cargo/config.toml (vendor redirect)"
echo ""

# ── Step 3: Run dpkg-buildpackage ─────────────────────────────────────────────
# Flags:
#   -us -uc  — unsigned source/changes (skip GPG for local builds)
#   -b       — binary-only build (don't produce .dsc / .tar.gz source pkg)
#   -jauto   — parallel jobs (auto-detect CPU count)
echo "🔨 Building .deb packages with dpkg-buildpackage..."
echo "   (This will take 1–5 minutes for release compilation)"
echo ""

dpkg-buildpackage -us -uc -b -jauto

# ── Step 4: Show results ───────────────────────────────────────────────────────
echo ""
echo "✅ Build complete!"
echo ""
echo "📦 Packages produced:"
find .. -maxdepth 1 -name 'tt-toplike*.deb' -exec ls -lh {} \;

echo ""
echo "🔍 Inspect a package:"
echo "   dpkg-deb --info ../tt-toplike_*.deb"
echo "   dpkg-deb --contents ../tt-toplike_*.deb"
echo ""
echo "💾 Install locally:"
echo "   sudo dpkg -i ../tt-toplike_*.deb"
echo "   tt-toplike --mock --mock-devices 4"
echo "   tt-toplike --mode arcade"
